### ISSUE TITLE
Windows 7?

### ISSUE THREAD

**Issue by gorimare64** [mininmobile/discord.bat.exe-source#1]
I have gotten you wonderful tool here working on my Windows 10 PC, but when I moved everything to my Windows 7 laptop, it say its connected however the bot remains offline on Discord. I was wondering if I missed something or if it just doesn't work with the operating system.

**Comment by MininMobile** [comment]
Do you have [.NET Framework 4.6.1](https://www.microsoft.com/en-us/download/details.aspx?id=49982) installed?

**Comment by gorimare64** [comment]
I only have .NET Framework 4.7.2. That must be the issue then. I will try that version and get back to you.

**Comment by gorimare64** [comment]
I have installed .NET Framework 4.6.1. This has not fixed the problem, the bot is still offline.

**Comment by mininmobile** [comment]
sucks to suck
